Search suggestion integration with elastic api

diff --git a/logstash/docker-compose-logstash.yml b/logstash/docker-compose-logstash.yml
--- a/logstash/docker-compose-logstash.yml
+++ b/logstash/docker-compose-logstash.yml
@@ -12,7 +12,8 @@ services:
       - ../shared/certs/logstash/logstash.crt:/usr/share/logstash/config/certs/logstash.crt:ro
       - ../shared/certs/logstash/logstash.key:/usr/share/logstash/config/certs/logstash.key:ro
       - logstashdata:/usr/share/logstash/data
-      - ./sample_data/test.json:/usr/share/logstash/input/test.json
+      - ./sample_data/previously_searched_sample.json:/usr/share/logstash/input/previously_searched_sample.json
+      - ./sample_data/search_suggestion_sample.json:/usr/share/logstash/input/search_suggestion_sample.json
     environment:
       - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_URL}
       - CA_CERTIFICATE_PATH=${CA_CERTIFICATE_PATH}
@@ -21,6 +22,10 @@ services:
 
       - PREVIOUSLY_SEARCHED_ITEM_TEMPLATE_NAME=${PREVIOUSLY_SEARCHED_ITEM_TEMPLATE_NAME}
       - PREVIOUSLY_SEARCHED_ITEM_INDEX_NAME=${PREVIOUSLY_SEARCHED_ITEM_INDEX_NAME}
+
+      - SEARCH_SUGGESTION_TEMPLATE_NAME=${SEARCH_SUGGESTION_TEMPLATE_NAME}
+      - SEARCH_SUGGESTION_INDEX_NAME=${SEARCH_SUGGESTION_INDEX_NAME}
+
       - PAGE_SIZE=${PAGE_SIZE}
     networks:
       - cmp-elastic
@@ -36,8 +41,18 @@ services:
         else
           echo "Ok"
         fi
-        echo "Launching the pipelines..."
-        bin/logstash -f pipeline/pipeline.conf
+        echo -n "Checking ${SEARCH_SUGGESTION_INDEX_NAME}...";
+        if ! curl -s -I --cacert ${CA_CERTIFICATE_PATH} -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}" ${ELASTICSEARCH_URL}/${SEARCH_SUGGESTION_INDEX_NAME} | grep -i -q "HTTP/1.1 200 OK"; then
+          echo "Not found";
+          echo "Creating ${SEARCH_SUGGESTION_INDEX_NAME}";
+          curl -X PUT --cacert ${CA_CERTIFICATE_PATH} -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}" "${ELASTICSEARCH_URL}/${SEARCH_SUGGESTION_INDEX_NAME}" -H "Content-Type: application/json" -d @templates/${SEARCH_SUGGESTION_ITEM_INDEX_TEMPLATE_FILE}
+        else
+          echo "Ok"
+        fi
+
+        echo "Injecting sample data..."
+        bin/logstash
+
       '
 
 volumes:
